### ISSUE TITLE
Stop using doHover?

### ISSUE THREAD

**Issue by dianlujitao** [fannheyward/coc-ecdict#45]
https://github.com/neoclide/coc.nvim/issues/1417

**Comment by Freed-Wu** [comment]
It seem that <https://github.com/iamcco/coc-zi> don't have this problem.

**Comment by fannheyward** [comment]
> It seems that https://github.com/iamcco/coc-zi don't have this problem

coc-zi also uses doHover to show the translate.

The main feature of `coc-ecdict` is using `doHover` to show translate, so I don't want to stop to use doHover.
